Traceback (most recent call last):
  File "fcn32_hands_solve.py", line 5, in <module>
    import caffe
  File "/home/minghuam/caffe-fcn/python/caffe/__init__.py", line 1, in <module>
    from .pycaffe import Net, SGDSolver
  File "/home/minghuam/caffe-fcn/python/caffe/pycaffe.py", line 13, in <module>
    from ._caffe import Net, SGDSolver
ImportError: libcudart.so.7.0: cannot open shared object file: No such file or directory
